name: Bygg pull request

on: 
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.2.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn package -e --batch-mode --file pom.xml -DtrimStackTrace=false
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
         
