name: Bygg pull request

on: 
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn package -e --batch-mode --settings ./.github/.m2/settings.xml --file pom.xml -DtrimStackTrace=false
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
         
