name: Publish release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: x-access-token

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # So if we split on '/' and take the 3rd value, we can get the release name.
        run: |
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          mvn -B versions:set -DnewVersion="${NEW_VERSION}" -DgenerateBackupPoms=false
          mvn -B clean deploy -DtrimStackTrace=false
